version: "3.9"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./seoul-competition-backend/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Seoul"
    ports:
      - 3306:3306
    networks:
      - server-network


  springboot:
    container_name: springboot
    build:
      context: ./seoul-competition-backend
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      FIFTY: ${FIFTY}
      SENIOR: ${SENIOR}
      API_KEY: ${API_KEY}
      TZ: "Asia/Seoul"
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    networks:
      - server-network


  fastapi:
    container_name: fastapi
    build:
      context: ./seoul-competition-ai
      dockerfile: Dockerfile
    volumes:
      - ./seoul-competition-ai:/server
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - springboot
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
